export const DarkColors = {
  foreground: '#d6deeb',
  background: '#011627',
  contrastBorder: '#122d42',
  focusBorder: '#122d42',
  widgetShadow: '#011627',
  selectionBackground: '#4373c2',
  errorForeground: '#EF5350',
  buttonBackground: '#7e57c2cc',
  buttonForeground: '#ffffffcc',
  buttonHoverBackground: '#7e57c2',
  dropdownBackground: '#011627',
  dropdownBorder: '#5f7e97',
  dropdownForeground: '#ffffffcc',
  inputBackground: '#0b253a',
  inputForeground: '#ffffffcc',
  inputBorder: '#5f7e97',
  inputPlaceholderForeground: '#5f7e97',
  inputOptionActiveBorder: '#ffffffcc',
  inputValidationErrorBackground: '#AB0300F2',
  inputValidationErrorBorder: '#EF5350',
  inputValidationInfoBackground: '#00589EF2',
  inputValidationInfoBorder: '#64B5F6',
  inputValidationWarningBackground: '#675700F2',
  inputValidationWarningBorder: '#FFCA28',
  scrollbarShadow: '#010b14',
  scrollbarSliderActiveBackground: '#084d8180',
  scrollbarSliderBackground: '#084d8180',
  scrollbarSliderHoverBackground: '#084d8180',
  badgeBackground: '#5f7e97',
  badgeForeground: '#ffffff',
  progressBarBackground: '#7e57c2',
  breadcrumbForeground: '#A599E9',
  breadcrumbFocusForeground: '#ffffff',
  breadcrumbActiveSelectionForeground: '#FFFFFF',
  breadcrumbPickerBackground: '#001122',
  listActiveSelectionBackground: '#234d708c',
  listActiveSelectionForeground: '#ffffff',
  listInvalidItemForeground: '#975f94',
  listDropBackground: '#011627',
  listFocusBackground: '#010d18',
  listFocusForeground: '#ffffff',
  listHighlightForeground: '#ffffff',
  listHoverBackground: '#011627',
  listHoverForeground: '#ffffff',
  listInactiveSelectionBackground: '#0e293f',
  listInactiveSelectionForeground: '#5f7e97',
  activityBarBackground: '#011627',
  activityBarDropBackground: '#5f7e97',
  activityBarForeground: '#5f7e97',
  activityBarBorder: '#011627',
  activityBarBadgeBackground: '#44596b',
  activityBarBadgeForeground: '#ffffff',
  sideBarBackground: '#011627',
  sideBarForeground: '#89a4bb',
  sideBarBorder: '#011627',
  sideBarTitleForeground: '#5f7e97',
  sideBarSectionHeaderBackground: '#011627',
  sideBarSectionHeaderForeground: '#5f7e97',
  editorGroupEmptyBackground: '#011627',
  editorGroupBorder: '#011627',
  editorGroupDropBackground: '#7e57c273',
  editorGroupHeaderNoTabsBackground: '#011627',
  editorGroupHeaderTabsBackground: '#011627',
  editorGroupHeaderTabsBorder: '#262A39',
  tabActiveBackground: '#0b2942',
  tabActiveForeground: '#d2dee7',
  tabBorder: '#272B3B',
  tabActiveBorder: '#262A39',
  tabUnfocusedActiveBorder: '#262A39',
  tabInactiveBackground: '#01111d',
  tabInactiveForeground: '#5f7e97',
  tabUnfocusedActiveForeground: '#5f7e97',
  tabUnfocusedInactiveForeground: '#5f7e97',
  editorBackground: '#011627',
  editorLineNumberForeground: '#4b6479',
  editorLineNumberActiveForeground: '#C5E4FD',
  editorCursorForeground: '#80a4c2',
  editorSelectionBackground: '#1d3b53',
  editorSelectionHighlightBackground: '#5f7e9779',
  editorInactiveSelectionBackground: '#7e57c25a',
  editorWordHighlightBackground: '#f6bbe533',
  editorWordHighlightStrongBackground: '#e2a2f433',
  editorFindMatchBackground: '#5f7e9779',
  editorFindMatchHighlightBackground: '#1085bb5d',
  editorHoverHighlightBackground: '#7e57c25a',
  editorLineHighlightBackground: '#0003',
  editorRangeHighlightBackground: '#7e57c25a',
  editorIndentGuideBackground: '#5e81ce52',
  editorIndentGuideActiveBackground: '#7E97AC',
  editorRulerForeground: '#5e81ce52',
  editorCodeLensForeground: '#5e82ceb4',
  editorOverviewRulerCurrentContentForeground: '#7e57c2',
  editorOverviewRulerIncomingContentForeground: '#7e57c2',
  editorOverviewRulerCommonContentForeground: '#7e57c2',
  editorErrorForeground: '#EF5350',
  editorWarningForeground: '#b39554',
  editorGutterBackground: '#011627',
  editorGutterModifiedBackground: '#e2b93d',
  editorGutterAddedBackground: '#9CCC65',
  editorGutterDeletedBackground: '#EF5350',
  editorInlayHintBackground: '#0000',
  editorInlayHintForeground: '#829D9D',
  diffEditorInsertedTextBackground: '#99b76d23',
  diffEditorInsertedTextBorder: '#c5e47833',
  diffEditorRemovedTextBackground: '#ef535033',
  diffEditorRemovedTextBorder: '#ef53504d',
  editorWidgetBackground: '#021320',
  editorWidgetBorder: '#5f7e97',
  editorSuggestWidgetBackground: '#2C3043',
  editorSuggestWidgetBorder: '#2B2F40',
  editorSuggestWidgetForeground: '#d6deeb',
  editorSuggestWidgetHighlightForeground: '#ffffff',
  editorSuggestWidgetSelectedBackground: '#5f7e97',
  editorHoverWidgetBackground: '#011627',
  editorHoverWidgetBorder: '#5f7e97',
  debugExceptionWidgetBackground: '#011627',
  debugExceptionWidgetBorder: '#5f7e97',
  editorMarkerNavigationBackground: '#0b2942',
  editorMarkerNavigationErrorBackground: '#EF5350',
  editorMarkerNavigationWarningBackground: '#FFCA28',
  peekViewBorder: '#5f7e97',
  peekViewEditorBackground: '#011627',
  peekViewEditorMatchHighlightBackground: '#7e57c25a',
  peekViewResultBackground: '#011627',
  peekViewResultFileForeground: '#5f7e97',
  peekViewResultLineForeground: '#5f7e97',
  peekViewResultMatchHighlightBackground: '#ffffffcc',
  peekViewResultSelectionBackground: '#2E3250',
  peekViewResultSelectionForeground: '#5f7e97',
  peekViewTitleBackground: '#011627',
  peekViewTitleDescriptionForeground: '#697098',
  peekViewTitleLabelForeground: '#5f7e97',
  mergeCurrentHeaderBackground: '#5f7e97',
  mergeIncomingHeaderBackground: '#7e57c25a',
  panelBackground: '#011627',
  panelBorder: '#5f7e97',
  panelTitleActiveBorder: '#5f7e97',
  panelTitleActiveForeground: '#ffffffcc',
  panelTitleInactiveForeground: '#d6deeb80',
  statusBarBackground: '#011627',
  statusBarForeground: '#5f7e97',
  statusBarBorder: '#262A39',
  statusBarDebuggingBackground: '#202431',
  statusBarDebuggingBorder: '#1F2330',
  statusBarNoFolderBackground: '#011627',
  statusBarNoFolderBorder: '#25293A',
  statusBarItemActiveBackground: '#202431',
  statusBarItemHoverBackground: '#202431',
  statusBarItemProminentBackground: '#202431',
  statusBarItemProminentHoverBackground: '#202431',
  titleBarActiveBackground: '#011627',
  titleBarActiveForeground: '#eeefff',
  titleBarInactiveBackground: '#010e1a',
  notificationsBackground: '#01111d',
  notificationsBorder: '#262a39',
  notificationCenterBorder: '#262a39',
  notificationToastBorder: '#262a39',
  notificationsForeground: '#ffffffcc',
  notificationLinkForeground: '#80CBC4',
  extensionButtonProminentForeground: '#ffffffcc',
  extensionButtonProminentBackground: '#7e57c2cc',
  extensionButtonProminentHoverBackground: '#7e57c2',
  editorForeground: '#d6deeb',
  pickerGroupForeground: '#d1aaff',
  pickerGroupBorder: '#011627',
  terminalAnsiWhite: '#ffffff',
  terminalAnsiBlack: '#011627',
  terminalAnsiBlue: '#6CC0FF',
  terminalAnsiCyan: '#21c7a8',
  terminalAnsiGreen: '#22da6e',
  terminalAnsiMagenta: '#EC7FFF',
  terminalAnsiRed: '#EF5350',
  terminalAnsiYellow: '#c5e478',
  terminalAnsiBrightWhite: '#ffffff',
  terminalAnsiBrightBlack: '#575656',
  terminalAnsiBrightBlue: '#6CC0FF',
  terminalAnsiBrightCyan: '#7fdbca',
  terminalAnsiBrightGreen: '#22da6e',
  terminalAnsiBrightMagenta: '#EC7FFF',
  terminalAnsiBrightRed: '#EF5350',
  terminalAnsiBrightYellow: '#ffeb95',
  terminalSelectionBackground: '#1b90dd4d',
  terminalCursorBackground: '#234d70',
  textCodeBlockBackground: '#4f4f4f',
  debugToolBarBackground: '#011627',
  welcomePageButtonBackground: '#011627',
  welcomePageButtonHoverBackground: '#011627',
  walkThroughEmbeddedEditorBackground: '#011627',
  welcomePageBackground: '#011627',
  gitDecorationModifiedResourceForeground: '#a2bffc',
  gitDecorationDeletedResourceForeground: '#EF535090',
  gitDecorationUntrackedResourceForeground: '#c5e478ff',
  gitDecorationIgnoredResourceForeground: '#395a75',
  gitDecorationConflictingResourceForeground: '#ffeb95cc',
  sourceElm: '#5f7e97',
  stringQuotedSingleJs: '#ffffff',
  metaObjectLiteralJs: '#6CC0FF',
  editorFindRangeHighlightBackground: null,
  editorLineHighlightBorder: null,
  editorLinkActiveForeground: null,
  editorWhitespaceForeground: null,
  editorErrorBorder: null,
  editorWarningBorder: null,
  mergeCurrentContentBackground: null,
  mergeIncomingContentBackground: null,
  mergeBorder: null,
  statusBarDebuggingForeground: null,
  statusBarNoFolderForeground: null,
  titleBarInactiveForeground: null,
  // Markup colors
  markupChanged: '#a2bffc',
  markupDeleted: '#EF535090',
  markupInserted: '#c5e478ff',

  // Comments
  comment: '#0d8633',
  doubleSlashedComment: '#0d8633',

  // global settings
  globalSettingsBackground: '#011627',
  globalSettingsForeground: '#d6deeb',

  // Variables and Values
  string: '#ecc48d',
  stringQuoted: '#ecc48d',
  supportConstantMath: '#c5e478',
  number: '#F78C6C',
  builtInConstant: '#6CC0FF',
  userDefinedConstant: '#6CC0FF',
  constantCharacterEscape: '#F78C6C',
  regExpString: '#5ca7e4',
  variable: '#c5e478',

  commaInFunctions: '#5f7e97',
  keyword: '#EC7FFF',
  storage: '#EC7FFF',
  storageType: '#EC7FFF',
  className: '#ffcb8b',
  inheritedClass: '#c5e478',
  functionName: '#EC7FFF',
  metaTag: '#7fdbca',

  // HTML
  htmlTagNames: '#caece6',
  tagAttributes: '#c5e478',
  entityNameTagCustom: '#f78c6c',

  libraryFunctionAndConstant: '#6CC0FF',
  supportConstantPropertyValueMeta: '#7fdbca',
  libraryClassType: '#c5e478',
  supportVariableDom: '#c5e478',
  invalidForeground: '#ffffff',
  invalidBackground: '#d3423e',
  // operators
  keywordOperator: '#7fdbca',
  keywordOperatorRelational: '#EC7FFF',
  keywordOperatorAssignment: '#EC7FFF',
  keywordOperatorArithmetic: '#EC7FFF',
  keywordOperatorBitwise: '#EC7FFF',
  keywordOperatorIncrement: '#EC7FFF',
  keywordOperatorTernary: '#EC7FFF',

  object: '#cdebf7',
  null: '#ff5874',
  metaBrace: '#d6deeb',
  metaDelimiterPeriod: '#EC7FFF',

  punctuationDefinitionString: '#d9f5dd',
  punctuationDefinitionStringMarkdown: '#ff5874',

  booleanFalse: '#ff5874',
  booleanTrue: '#3FBF7F',

  objectComma: '#ffffff',
  variableParameterFunction: '#7fdbca',
  supportTypePropertyNameAndEntityTags: '#80CBC4',
  entityNameTagReferenceInStylesheets: '#57eaf1',
  constantOtherColorRGBValuePunctuationDefinition: '#F78C6C',
  constantOtherColor: '#FFEB95',
  keywordOtherUnit: '#FFEB95',
  metaSelector: '#EC7FFF',
  entityOtherAttributeNameId: '#FAD430',
  metaPropertyName: '#80CBC4',
  doctypes: '#EC7FFF',
  punctuationDefinitionParameters: '#d9f5dd',
  keywordControlOperator: '#7fdbca',
  keywordOperatorLogical: '#EC7FFF',
  variableInstance: '#baebe2',
  variablePropertyOtherObjectProperty: '#faf39f',
  variablePropertyOtherObject: '#ffffff',
  entityNameFunction: '#6CC0FF',
  keywordOperatorComparison: '#EC7FFF',
  keywordControlConditional: '#EC7FFF',
  supportConstant: '#7fdbca',
  supportFunction: '#c5e478',
  invalidBrokenForeground: '#020e14',
  invalidBrokenBackground: '#F78C6C',
  invalidUnimplementedBackground: '#8BD649',
  invalidUnimplementedForeground: '#ffffff',
  invalidIllegalForeground: '#ffffff',
  invalidIllegalBackground: '#ec5f67',
  variableLanguage: '#7fdbca',
  supportVariableProperty: '#7fdbca',
  variableFunction: '#6CC0FF',
  variableInterpolation: '#ec5f67',
  metaFunctionCall: '#6CC0FF',
  punctuationSectionEmbedded: '#d3423e',
  punctuationTweaks: '#d6deeb',
  morePunctuationTweaks: '#d9f5dd',
  templateStrings: '#d3423e',
  backticsInTemplateStrings: '#d6deeb',
  italics: '#EC7FFF',
  bold: '#c5e478',
  quote: '#697098',
  rawCode: '#80CBC4',

  // CoffeeScript specific colors
  coffeeScriptVariableAssignment: '#31e1eb',
  coffeeScriptParameterFunction: '#d6deeb',
  coffeeScriptAssignments: '#7fdbca',

  // C# specific colors
  csharpReadwriteVariables: '#d6deeb',
  csharpClassesAndStorageTypes: '#ffcb8b',
  csharpNamespace: '#B2CCD6',
  csharpUnquotedString: '#d6deeb',
  csharpRegion: '#ffcb8b',
  csharpOtherVariable: '#B2CCD6',
  csharpEnum: '#c5e478',
  csharpUnquotedStringZone: '#d6deeb',
  csharpOtherVariables: '#B2CCD6',

  // dart
  dartString: '#FFCB8B',
  dartClass: '#FFCB8B',

  // CSS
  tagNamesInStylesheets: '#ff6363',
  wildcardSelectorInStylesheets: '#7fdbca',
  cssKeywordOtherUnit: '#FFEB95',
  attributeNameForCSS: '#F78C6C',

  elixirClasses: '#6CC0FF',
  elixirFunctions: '#c5e478',
  elixirConstants: '#6CC0FF',
  elixirStringPunctuations: '#c5e478',
  elixir: '#c5e478',
  elixirBinaryPunctuations: '#EC7FFF',
  closureConstantKeyword: '#7fdbca',
  // GO
  goFunctionCalls: '#DDDDDD',
  goKeywords: '#EC7FFF',

  goConstants: '#ff5874',
  cppFunctions: '#7fdbcaff',
  cppMetaNamespace: '#e0dec6',
  cppLanguagePrimitiveStorage: '#ff5874',
  cppPreprocessorMacro: '#d6deeb',
  cppVariableParameter: '#ffcb8b',
  powershellVariables: '#6CC0FF',
  powershellFunction: '#7fdbcaff',
  idAttributeNameHtml: '#c5e478',
  htmlPunctuationDefinitionTag: '#6ae9f0',
  htmlDoctype: '#EC7FFF',
  javascriptClasses: '#ffcb8b',
  javascriptMethodDeclaration: '#6CC0FF',
  javascriptTerminator: '#d6deeb',
  javascriptMetaPunctuationDefinition: '#d6deeb',
  entityNamesInCodeDocumentations: '#938e85',
  otherVariablesInCodeDocumentations: '#78ccf0',

  // JavaScript module imports and exports
  jsModuleImportsExports: '#d6deeb',

  // JavaScript Variable Parameter Function
  jsVariableParameterFunction: '#7986E7',

  // JavaScript[React] Variable Other Object
  jsReactVariableOtherObject: '#d6deeb',

  // JavaScript Variables
  jsVariables: '#d6deeb',

  jsVariableOtherReadWrite: '#d7dbe0',

  // JavaScript Entity Name Type
  jsEntityNameType: '#ffcb8b',

  // JavaScript Support Classes
  jsSupportClasses: '#d6deeb',

  // JSON Property Names
  jsonPropertyNames: '#7fdbca',

  // JSON Support Constants
  jsonSupportConstants: '#c5e478',

  // JSON Property values (string)
  jsonPropertyValuesString: '#c789d6',

  // Strings in JSON values
  jsonStringsInValues: '#80CBC4',

  // Specific JSON Property values like null
  jsonPropertyValuesNull: '#ff5874',

  // JavaScript Other Variable
  jsOtherVariable: '#7fdbca',
  jsOtherVariableItalic: '#7fdbca',
  jsEntityNamesInCodeDocumentations: '#938e85',
  jsOtherVariablesInCodeDocumentations: '#78ccf0',
  jsSupportClassComponent: '#f78c6c',
  jsTextNestedInReactTags: '#d6deeb',

  // Ruby Variables
  rubyVariables: '#d6deeb',

  // Ruby Class
  rubyClass: '#ecc48d',
  rubyHashkeys: '#7fdbca',
  rubySymbols: '#7fdbca',

  // Less
  lessTagNames: '#7fdbca',
  lessKeywordOtherUnit: '#FFEB95',
  attributeNameForLess: '#F78C6C',
  markdownHeadings: '#82b1ff',
  markdownItalics: '#EC7FFF',
  lessAttributeName: '#F78C6C',

  // Markdown
  markdownBold: '#c5e478',
  markdownQuote: '#697098',
  markdownRawCode: '#80CBC4',
  markdownLinks: '#ff869a',
  markdownLinkTitleDescription: '#d6deeb',
  markdownPunctuation: '#82b1ff',
  markdownMetaDataPunctuation: '#7fdbca',
  markdownListPunctuation: '#82b1ff',
  markdownInlineRawString: '#c5e478',

  // PHP
  phpVariables: '#bec5d4',
  phpSupportClass: '#ffcb8b',
  phpFunctionCallPunctuation: '#d6deeb',
  phpGlobalVariables: '#c5e478',
  phpGlobalVariablePunctuation: '#c5e478',

  // python
  pythonLanguageConstant: '#ff5874',
  pythonFunctionParameter: '#6CC0FF',
  pythonFunctionCall: '#B2CCD6',
  pythonPunctuation: '#d6deeb',
  pythonDecoratorFunction: '#c5e478',
  pythonLanguageVariable: '#8EACE3',
  pythonImportControlKeyword: '#EC7FFF',
  scssVariable: '#c5e478',
  variablesInSassAtRules: '#6CC0FF',
  variablesInSassAtRulesAlt: '#bec5d4',
  attributeNameForSass: '#F78C6C',
  scssTagNames: '#7fdbca',
  sassKeywordOtherUnit: '#FFEB95',
  // TypeScript
  typescriptVariables: '#d6deeb',
  typescriptEntityNameTypes: '#ffcb8b',
  typescriptNodeClasses: '#6CC0FF',
  typescriptEntityNameTypesAsParameters: '#938e85',
  typescriptImportExportPunctuations: '#d6deeb',
  typescriptPunctuationDecorators: '#6CC0FF',
  typescriptPunctuationDecoratorsJsx: '#6CC0FF',
  typescriptClasses: '#ffcb8b',
  typescriptEntityNameType: '#ffcb8b',
  typescriptClassVariableKeyword: '#EC7FFF',
  typescriptMethodDeclaration: '#6CC0FF',

  yamlEntityNameTags: '#7fdbca',
  markupDeletedDiff: '#EF535090',
  markupInsertedDiff: '#c5e478ff',
  attributeNameForCss: '#F78C6C',
}